### ISSUE TITLE
Error executing: gn gen out/ios_64....

### ISSUE THREAD

**Issue by aurdoc** [tkmn0/SimpleWebRTCExample_iOS#16]
Excellent instructions to generate WebRTC framework... thanks!  I am trying to build the framework on a iMac with OS: 10.15.4 (I think is beta 4) and Xcode 11.4 (released)...  I am very unfamiliar with the google tools and I hope to not have to learn; I prefer to be able to build my own framework. 

after downloading m79 and "sync -D" I am trying to generate the 64 bit version and I get the following error:
=================================================================

aurel@Gaon src % gn gen out/ios_64 --args='target_os="ios" target_cpu="arm64" is_debug=false ios_enable_code_signing=false'
ERROR at //build/config/ios/ios_sdk.gni:94:21: Script returned non-zero exit code.
  _ios_sdk_result = exec_script(script_name, ios_sdk_info_args, "scope")
                    ^----------
Current dir: /Volumes/nev/webRTC/webrtc_build/src/out/ios_64/
Command: python /Volumes/nev/webRTC/webrtc_build/src/build/config/mac/sdk_info.py --get_sdk_info iphoneos
Returned 1.
stderr:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Traceback (most recent call last):
  File "/Volumes/nev/webRTC/webrtc_build/src/build/config/mac/sdk_info.py", line 106, in <module>
    FillXcodeVersion(settings, args.developer_dir)
  File "/Volumes/nev/webRTC/webrtc_build/src/build/config/mac/sdk_info.py", line 57, in FillXcodeVersion
    lines = subprocess.check_output(['xcodebuild', '-version']).splitlines()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['xcodebuild', '-version']' returned non-zero exit status 1

See //build/config/sysroot.gni:67:3: whence it was imported.
  import("//build/config/ios/ios_sdk.gni")
  ^--------------------------------------
See //build/config/linux/pkg_config.gni:5:1: whence it was imported.
import("//build/config/sysroot.gni")
^----------------------------------
See //BUILD.gn:15:1: whence it was imported.
import("//build/config/linux/pkg_config.gni")
^-------------------------------------------
aurel@Gaon src % 
===================================================================
any suggestion on how to fix?  thanks!

**Comment by aurdoc** [comment]
mea culpa:  for some crazy reasons I was trying to use m79 branch instead of recommended 72... everything works right after downloading the 72 branch
